### PR TITLE
fix: description trimming & htmlEncode

### LINKED ISSUE #20: Showing .. after the repo description
idk why it's showing .. after every repo description. It's looks wierd.

Screenshot 2020-07-11 at 1 21 26 PM

### PR DESCRIPTION
**Pull request by anuraghazra**
fixes #20 
fixes SVG rendering failing because of special characters in the description

### CODE REVIEW

File: api/pin.js [hunk 1]
```diff
@@ -94,11 +91,8 @@ const renderRepoCard = (repo) => {
       </svg>
 
       <text x="50" y="38" class="header">${name}</text>
-      <text class="description" x="25" y="70">${
-        description ? description.slice(0, 60) : "No description provided"
-      }..</text>
+      <text class="description" x="25" y="70">${encodeHTML(desc)}</text>
```
Comment (anuraghazra) [inline api/pin.js:94]: HTML encode the description to prevent failing SVG
